FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY package.json ./

# Install dependencies
RUN yarn install

# Copy frontend code
COPY . .

# Expose port
EXPOSE 3000

# Set environment variable
ENV CHOKIDAR_USEPOLLING=true

# Start the development server
CMD ["yarn", "start"]